# Generated by Django 3.1.2 on 2020-10-23 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_status', models.CharField(choices=[('waiting', 'waiting'), ('running', 'running'), ('complete', 'complete'), ('fail', 'fail'), ('stop', 'stop')], default='waiting', max_length=100)),
                ('smiles', models.TextField()),
                ('job_explanation', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('module_type', models.CharField(choices=[('type1', 'type1'), ('type2', 'type2')], max_length=100)),
                ('module_img', models.ImageField(blank=True, upload_to='job_user/module')),
                ('module_level', models.CharField(choices=[('1', 'level1'), ('2', 'level2'), ('3', 'level3')], default='1', max_length=100)),
                ('module_explanation', models.TextField()),
                ('module_category', models.CharField(choices=[('category1', 'category1'), ('category2', 'category2')], max_length=100)),
                ('paper_link', models.URLField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'module',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModuleApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_api_name', models.CharField(max_length=100)),
                ('module_api_cd', models.CharField(default='CD001', max_length=10)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_user.module')),
            ],
            options={
                'db_table': 'moduleapi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_user.job')),
            ],
            options={
                'db_table': 'jobResult',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='module_api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_user.moduleapi'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('module', models.ManyToManyField(to='job_user.Module')),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
    ]
