# Generated by Django 4.0.3 on 2022-03-31 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_user.job')),
                ('module_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_user.moduleapi')),
            ],
            options={
                'db_table': 'jobModule',
                'managed': True,
            },
        ),
    ]
