# Generated by Django 4.0.3 on 2022-03-31 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_user', '0002_jobmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresult',
            name='module_api',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='job_user.jobmodule'),
            preserve_default=False,
        ),
    ]
