# Generated by Django 4.0.3 on 2022-04-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_user', '0003_jobresult_module_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='module_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_user.moduleapi'),
        ),
    ]
